# Site settings
title: Sean Rice - Senior Lead User Experience Designer | SeanRice.net
email:
description: Sean Rice is a design leader working remotely from Pennsylvania. This site houses a history of his work and writings.
#baseurl: "https://seanriceaz.github.io"
url: "https://seanrice.net" # the base hostname & protocol for your site
github_username:  seanriceaz

#plugins: #comment this out when developing. Uncomment when deploying.
# - jekyll-redirect-from

# Build settings
markdown: kramdown
# Sass
sass:
  sass_dir: _sass
  style: :compressed
  line_numbers: false
